# Generated by Django 2.2.5 on 2019-10-01 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bell',
            name='link_ref',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
