# Generated by Django 2.2.5 on 2019-10-02 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bell', '0002_bell_link_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bell.Bell')),
            ],
        ),
    ]
