# Generated by Django 2.2.5 on 2019-10-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
