# Generated by Django 2.2.5 on 2019-10-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell', '0004_event_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='bell',
            name='title',
            field=models.CharField(blank=True, default='Без названия', max_length=255, null=True),
        ),
    ]
