# Generated by Django 2.2.5 on 2019-10-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell', '0005_bell_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
